# Generated by Django 4.1.3 on 2022-11-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Group",
            field=models.CharField(
                choices=[
                    ("-", "-"),
                    ("КИ19-11Б", "ки19-11б"),
                    ("КИ19-12Б", "ки19-12б"),
                    ("КИ19-13Б", "ки19-13б"),
                    ("КИ19-14Б", "ки19-14б"),
                    ("КИ19-15Б", "ки19-15б"),
                    ("КИ20-11Б", "ки20-11б"),
                    ("КИ20-12Б", "ки20-12б"),
                ],
                default="-",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="Sex",
            field=models.CharField(
                choices=[("-", "-"), ("М", "Мужской"), ("Ж", "Женский")],
                default="-",
                max_length=4,
            ),
        ),
    ]
