# Generated by Django 4.1.3 on 2022-11-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_remove_student_ismarried_student_familystatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student", name="Age", field=models.IntegerField(default="-"),
        ),
        migrations.AlterField(
            model_name="student",
            name="Name",
            field=models.CharField(default="-", max_length=200),
        ),
    ]
