# Generated by Django 4.1.3 on 2022-11-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0005_alter_student_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student", name="Age", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="student", name="Name", field=models.CharField(max_length=200),
        ),
    ]
