# Generated by Django 4.1.3 on 2022-11-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0008_groupmodel_studentmodel_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("sex", models.CharField(max_length=15)),
                ("age", models.IntegerField()),
                ("group", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(model_name="studentmodel", name="group",),
        migrations.DeleteModel(name="GroupModel",),
        migrations.DeleteModel(name="StudentModel",),
    ]
