# Generated by Django 4.1.3 on 2022-11-09 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0011_todo_delete_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 9, 17, 48, 32, 237411),
                verbose_name="Время создания",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
