# Generated by Django 4.1.3 on 2022-11-09 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0012_todo_created_todo_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 10, 17, 56, 26, 860599),
                verbose_name="Крайний срок",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 9, 17, 56, 26, 860599),
                verbose_name="Время создания",
            ),
        ),
    ]
