# Generated by Django 4.1.3 on 2022-11-09 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0013_todo_deadline_alter_todo_created"),
    ]

    operations = [
        migrations.RemoveField(model_name="todo", name="deadline",),
        migrations.AlterField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 9, 18, 12, 4, 316213),
                verbose_name="Время создания",
            ),
        ),
    ]
