# Generated by Django 4.1.3 on 2022-11-09 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0014_remove_todo_deadline_alter_todo_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 9, 18, 18, 35, 509075),
                verbose_name="Время создания",
            ),
        ),
    ]
