# Generated by Django 4.1.3 on 2022-11-10 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0017_alter_todo_created_alter_todo_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 10, 18, 53, 47, 526300),
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="todo", name="description", field=models.TextField(null=True),
        ),
    ]
