# Generated by Django 4.1.3 on 2022-11-10 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0018_alter_todo_created_alter_todo_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 10, 21, 43, 31, 319240),
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="todo", name="deadline", field=models.DateField(null=True),
        ),
    ]
