# Generated by Django 4.1.3 on 2022-11-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0019_alter_todo_created_alter_todo_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(
                default="11/10/2022", verbose_name="Время создания"
            ),
        ),
    ]
